# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee506c2948d72afbd122aa1628893a991a1d8fb33b345c81857b4c4d457f935ce41831dfc2604fc27b0848ed29277e3694e1d8abe9c662bff87f857d90c505e0

test:
  secret_key_base: e43f87ddeb1f0babe4007f517ab633b4e653a59aecc4e9f5ebe13d7f686d19a34e86b763a42a6e7ed2e1694cdd494ef265d05c0a4b0f0a560309b118ab766392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
